apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: mycluster-secret
  ## Specify additional volume specification
  volumeSpec:
    # https://godoc.org/k8s.io/api/core/v1#PersistentVolumeClaimSpec
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi

---

apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: wordpressdb
spec:
  database: wordpressdb
  clusterRef:
    name: my-cluster
    namespace: mysql

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: wordpress-user-one
spec:
  user: wordpress-user-one
  clusterRef:
    name: my-cluster
    namespace: mysql
  password:
    name: wordpress-user-one
    key: changeit
  allowedHosts:
    - wordpress-svc
  permissions:
    - schema: wordpressdb
      tables: ["*"]
      permissions:
        - SELECT
        - UPDATE
        - CREATE
        - DELETE