apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
spec:
  selector:
    app: bggapp-deploy-po
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer