apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  labels:
    name: bggapp-secret
  namespace: bggns
type: Opaque
data:
  # echo -n changeit | baset64 -w0 -
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=