apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol
  labels:
    name: my-vol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "do-block-storage" 
  volumeName: my-vol

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  hosts: |
    Hi! Bye!

  readme.txt: Please find me!