apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpressapp-cm
  labels:
    name: wordpressapp-cm
  namespace: wordpress
data:
   WORDPRESS_DB_HOST: my-cluster-mysql
   WORDPRESS_DB_USER: wordpress-user-one
   WORDPRESS_DB_NAME: wordpressdb